# Generated by Django 6.1.2 on 2026-10-07 09:47

import assessments.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(120)])),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('height_cm', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(30)])),
                ('weight_kg', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('mallampati', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('upper_lip_bite', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('neck_movement', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=100)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.CharField(choices=[('front', 'Front view'), ('mallampati', 'Mallampati view'), ('open_mouth', 'Open mouth view'), ('side', 'Side view')], max_length=20)),
                ('image', models.ImageField(upload_to=assessments.models.photo_path)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='assessments.assessment')),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='assessments.device'),
        ),
    ]
