# Generated by Django 6.1.2 on 2026-10-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='mallampati',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='upper_lip_bite',
        ),
        migrations.AlterField(
            model_name='assessment',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='neck_movement',
            field=models.CharField(choices=[('normal', 'Normal'), ('limited', 'Limited')], max_length=10),
        ),
    ]
