# Generated by Django 6.1.2 on 2026-10-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_remove_assessment_mallampati_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='previous_difficult_intubation',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', "Don't know")], default='unknown', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assessmentphoto',
            name='position',
            field=models.CharField(choices=[('front', 'Front view'), ('mallampati', 'Mallampati view'), ('open_mouth', 'Open mouth view'), ('side', 'Side view'), ('upper_lip_bite', 'Upper lip bite view'), ('head_back_side', 'Head back side view')], max_length=20),
        ),
    ]
